const tarotCards = [
	'Głupiec',
  'Mag',
  'Papieżyca',
  'Cesarzowa',
  'Cesarz',
  'Papież',
  'Kochankowie',
  'Rydwan',
  'Sprawiedliwość',
  'Eremita',
  'Koło Fortuny',
  'Siła',
  'Wisielec',
  'Śmierć',
  'Umiarkowanie',
  'Diabeł',
  'Wieża',
  'Gwiazda',
  'Księżyc',
  'Słońce',
  'Sąd Ostateczny',
  'Świat',
  'Królowa Pucharów',
  'Królowa Mieczy',
  'Królowa Monet',
  'Królowa Kijów',
  'Król Pucharów',
  'Król Mieczy',
  'Król Monet',
  'Król Kijów',
  'Rycerz Pucharów',
  'Rycerz Mieczy',
  'Rycerz Monet',
  'Rycerz Kijów',
  'Pajes Pucharów',
  'Pajes Mieczy',
  'Pajes Monet',
  'Pajes Kijów',
  'As Pucharów',
  'As Mieczy',
  'As Monet',
  'As Kijów',
  '2 Pucharów',
  '2 Mieczy',
  '2 Monet',
  '2 Kijów',
  '3 Pucharów',
  '3 Mieczy',
  '3 Monet',
  '3 Kijów',
  '4 Pucharów',
  '4 Mieczy',
  '4 Monet',
  '4 Kijów',
  '5 Pucharów',
  '5 Mieczy',
  '5 Monet',
  '5 Kijów',
  '6 Pucharów',
  '6 Mieczy',
  '6 Monet',
  '6 Kijów',
  '7 Pucharów',
  '7 Mieczy',
  '7 Monet',
  '7 Kijów',
  '8 Pucharów',
  '8 Mieczy',
  '8 Monet',
  '8 Kijów',
  '9 Pucharów',
  '9 Mieczy',
  '9 Monet',
  '9 Kijów',
  '10 Pucharów',
  '10 Mieczy',
  '10 Monet',
  '10 Kijów',
];

export default tarotCards;
